### ISSUE TITLE
支持其他网卡

### ISSUE THREAD

**Issue by lelemka0** [yujincheng08/mlx4_br#1]
您好，想请问这个存储库解决的是否是这个问题：pf/vf加入的网桥无法与vf通信
https://forum.proxmox.com/threads/communication-issue-between-sriov-vm-vf-and-ct-on-pf-bridge.68638/
这不是mellanox网卡独有的问题，intel的网卡也存在，向fdb添加mac地址的方法也适用于其他网卡。

**Comment by yujincheng08** [comment]
我没有其他网卡所以无法判断驱动名字。你可以试一下把这行改成 intel 的驱动名字然后编译试试

https://github.com/yujincheng08/mlx4_br/blob/07468ab7c50d865c8bc3acbe137b689e7e41ad13/main.cc#L746

**Comment by yujincheng08** [comment]
https://github.com/yujincheng08/mlx4_br/commit/b29633b0bd0d8aa7b16f928afae283ae9e5ab7ec

这个应该才对。
