### ISSUE TITLE
能不能添加个支持X520万兆卡的vf驱动？

### ISSUE THREAD

**Issue by cyinan** [yujincheng08/mlx4_br#3]
能不能添加个支持X520万兆卡的vf驱动？我底层是unraid,虚拟的win10直通了vf口，访问外网都正常，但是无法访问内网包括unraid以及所有docker的IP，你这个openwrt下我试了，驱动好像没用，还是识别不了vf网口

**Comment by yujincheng08** [comment]
需要知道驱动叫什么名字

**Comment by yujincheng08** [comment]
应该已经支持了。
